version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: networking-postgres
    environment:
      POSTGRES_USER: networking
      POSTGRES_PASSWORD: networking_password
      POSTGRES_DB: networking
      # Optimizations
      POSTGRES_MAX_CONNECTIONS: 200
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U networking -d networking"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: networking-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Modules Engine (Python Primitives)
  modules-engine:
    build:
      context: ./modules-engine
      dockerfile: Dockerfile.modules
    container_name: networking-modules-engine
    ports:
      - "8081:8081"
    environment:
      - MODULES_ENGINE_PORT=8081
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
