package middleware

import (
	"networking-main/pkg/nexus"

	"github.com/gin-gonic/gin"
)

// NexusTracker intercepts requests to record metrics for the visualizer
func NexusTracker() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Record Request Start
		nexus.NexusHub.RecordRequest()

		c.Next()

		// Record Request End
		nexus.NexusHub.RecordResponse()

		// If blocked (e.g., 429 Too Many Requests or 403 Forbidden generated by other middleware)
		if c.Writer.Status() == 429 || c.Writer.Status() == 403 {
			nexus.NexusHub.RecordBlock()
		}
	}
}
